<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Email ID  Mobile Number_ng-tns-c110-2 ng-_7e3268</name>
   <tag></tag>
   <elementGuidId>a81b2ac1-6f2e-48d1-86e3-7cc566445b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ng-tns-c110-2.ng-star-inserted.pi.pi-eye-slash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/mat-card-content/form/div[2]/span/p-password/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5c1fe956-2c8b-45f4-91d2-1db6ce7f12ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c110-2 ng-star-inserted pi pi-eye-slash</value>
      <webElementGuid>0c2f2803-af2d-4dc3-b03f-2875da48e4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c116-5 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;p-field&quot;]/span[@class=&quot;p-float-label&quot;]/p-password[@class=&quot;p-element p-inputwrapper ng-tns-c110-2 ng-star-inserted p-inputwrapper-filled ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;ng-tns-c110-2 p-password p-component p-inputwrapper p-input-icon-right&quot;]/i[@class=&quot;ng-tns-c110-2 ng-star-inserted pi pi-eye-slash&quot;]</value>
      <webElementGuid>3fe24f6e-dd52-42cd-ba6a-f470742c2a9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/mat-card-content/form/div[2]/span/p-password/div/i</value>
      <webElementGuid>fcde6964-72b8-4e5f-ae73-a9dace1434e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>863d688d-f323-4f22-a0f4-6d80579d6089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
