<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EnglishLanguage</name>
   <tag></tag>
   <elementGuidId>6541249b-096d-47b8-846b-170becaaa739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e27f2af5-2b10-4f74-82bc-b4c7fa5c1636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c87-0</value>
      <webElementGuid>9adbc00d-a239-40fb-9b19-6c8d583c2556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EnglishLanguage</value>
      <webElementGuid>bdd5b80c-6c65-464d-b3d2-4733a6841ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;core-container&quot;]/div[@class=&quot;language-select&quot;]/app-language-select[1]/mat-form-field[@class=&quot;mat-form-field language ng-tns-c87-0 mat-accent mat-form-field-type-mat-select mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label ng-untouched ng-pristine ng-valid ng-star-inserted mat-form-field-should-float&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-0&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-0&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-0&quot;]</value>
      <webElementGuid>4c4caeb2-616f-41df-abd8-bb6e97d83e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>2363de5e-c74f-4236-8883-f9cff23623ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EnglishLanguage' or . = 'EnglishLanguage')]</value>
      <webElementGuid>1c9fd787-8ff2-427a-b838-d1cc12394f16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
