<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Email ID  Mobile NumberPassword Login _80b284</name>
   <tag></tag>
   <elementGuidId>d4f15334-fb22-4a70-8860-01f188f0852b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/mat-card-content/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>cb4ce2bb-710b-4989-acf1-54fb20d50e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.gt-md</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>982f6584-58f8-4dbf-9de2-8d85ee267ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.md</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>82e0b07f-8da9-4a1e-8470-014ac5032404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.sm</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>610d96c1-42b6-4c98-a304-d2060dea5a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.xs</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>2d525f87-7621-40a4-9103-bc29d419e0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>7f7f6334-31bd-4470-a9dd-9cb7c188879e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutalign</name>
      <type>Main</type>
      <value>center stretch</value>
      <webElementGuid>8c10cc31-0cc6-4951-aa3c-3e00ce3ce904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutgap</name>
      <type>Main</type>
      <value>5px</value>
      <webElementGuid>7738ee55-fd25-4978-aa67-4e3e7a31408a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8f6408a3-f883-482b-969b-c56a85c764db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email ID / Mobile NumberPassword Login  Or  Login with OTP  Forgot Password? </value>
      <webElementGuid>fadc9591-714c-4f13-8b7d-ba14b56d90bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c116-5 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>e3ebd046-9bd7-45f8-98a6-11cdaed95433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/mat-card-content/form</value>
      <webElementGuid>979a10c4-6632-4cca-b20a-71834f770c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dual Login'])[1]/following::form[1]</value>
      <webElementGuid>f25a61af-a344-4727-98fc-1a7027f953c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Login'])[1]/following::form[1]</value>
      <webElementGuid>5245d974-b14f-4d3b-8b72-f9f4bd08082f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>fc0f3542-5612-4164-a021-dbb54fb20c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Email ID / Mobile NumberPassword Login  Or  Login with OTP  Forgot Password? ' or . = 'Email ID / Mobile NumberPassword Login  Or  Login with OTP  Forgot Password? ')]</value>
      <webElementGuid>234c3002-8a11-4418-876f-044ae72c0cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
