<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_EmailHomePage</name>
   <tag></tag>
   <elementGuidId>b959960d-a290-47c7-aa0c-e45899afa35c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Form_submitForm_EmailHomePage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Form_submitForm_EmailHomePage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4027a81d-1448-41ba-9bbe-dfc31c82306f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>59b1201c-c7de-4528-8df2-5a47a1451791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailHomePage</value>
      <webElementGuid>96ea0494-65f2-43e0-9527-3531b660bdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email text tryit-email</value>
      <webElementGuid>4d1dff72-069b-463a-b2bf-e489c98978fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form_submitForm_EmailHomePage</value>
      <webElementGuid>d7754875-76c6-40fd-9990-12e28b65f78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>96ec653b-f675-46dc-92f2-aaf3e0ff6adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email address here</value>
      <webElementGuid>f0f73b7f-ac31-4b46-9ce8-f137d86ff0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form_submitForm_EmailHomePage&quot;)</value>
      <webElementGuid>4879299a-c8db-44b3-abd4-0347947f9f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Form_submitForm_EmailHomePage']</value>
      <webElementGuid>feddd8f4-99a6-47fd-a876-4e1b4eeda438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Form_submitForm_EmailHomePage_Holder']/div/input</value>
      <webElementGuid>559c6170-8353-47f1-8c1e-00fa32ccf9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0eed25a2-0c95-46cc-b061-f9f17d004c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'EmailHomePage' and @id = 'Form_submitForm_EmailHomePage' and @placeholder = 'Enter your email address here']</value>
      <webElementGuid>4fda6ef4-b80c-4386-89e9-a66de7da0b1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
