name: CI
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '9.3.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -statusDelay=15 -testSuiteCollections="Test Suites\Functional_Testsuite" -apiKey="${{secrets.KATALON_API_KEY}} --config -webui.autoUpdateDrivers=true'
